### ISSUE TITLE
contribute to check a given string is palindrome or not

### ISSUE THREAD

**Issue by Priyanshu-792** [Priyanshu-792/Hactober_DSA#10]

**Comment by PikuSpeaks123** [comment]
Hey @Priyanshu-79 can  you assign me?

**Comment by Sajal193** [comment]
can you please assign it to me @Priyanshu-792 ?

**Comment by Priyanshu-792** [comment]
@Sajal193 I am assigning this work to you ... all the best!

**Comment by Priyanshu-792** [comment]
@Sajal193 have you contributed on this issue??

**Comment by Sajal193** [comment]
I'll make PRs today...thank you
