### ISSUE TITLE
Contribute any program from arrays, strings 

### ISSUE THREAD

**Issue by Priyanshu-792** [Priyanshu-792/Hactober_DSA#27]
In any language of code is accepted ....it should rum successfully and give a desired output

**Comment by void-57** [comment]
Please assign me

**Comment by void-57** [comment]
Hey @Priyanshu-792 please assign me

**Comment by 1anshu-56** [comment]
Hey @Priyanshu-792 
I would like to contribute on this issue, please assign me.

**Comment by SakshiMishra1** [comment]
please check PR #31

**Comment by ShreyaShukla03** [comment]
please check PR #33

**Comment by HPatel08** [comment]
Kindly check my PR #32

**Comment by UstitvaG** [comment]
hello, i would like to work on this issue. 
could you assign this issue to me?

**Comment by ankit-singh02** [comment]
Please Check PR #36

**Comment by Priyanshu-792** [comment]
@1anshu-56 you may go ahead to contribute on this issue as i have already assigned it to you
