### ISSUE TITLE
Contribute on Trees dsa

### ISSUE THREAD

**Issue by Priyanshu-792** [Priyanshu-792/Hactober_DSA#9]
Any tree dsa is accepted on any language.

**Comment by poorvaditya18** [comment]
Hey , I would like to work on this issue .

**Comment by nitingarg2207** [comment]
Hey, @Priyanshu-792 I would like to work on this issue, can you assign this to me.

**Comment by Priyanshu-792** [comment]
> Hey, @Priyanshu-792 I would like to work on this issue, can you assign this to me.

yo can even contribute to this

**Comment by Priyanshu-792** [comment]
you can even contribute to this
